///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Sid_FCGAProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The KillExcelChromeProcess recording.
    /// </summary>
    [TestModule("e38a35a2-91f5-4146-8c01-9f5b87dfee43", ModuleType.Recording, 1)]
    public partial class KillExcelChromeProcess : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repository.
        /// </summary>
        public static global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository repo = global::Sid_FCGAProject.Project_Repository.Sid_FCGAProjectRepository.Instance;

        static KillExcelChromeProcess instance = new KillExcelChromeProcess();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public KillExcelChromeProcess()
        {
            ChromeProcessName = "chrome";
            ExcelProcessName = "Excel";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static KillExcelChromeProcess Instance
        {
            get { return instance; }
        }

#region Variables

        string _ChromeProcessName;

        /// <summary>
        /// Gets or sets the value of variable ChromeProcessName.
        /// </summary>
        [TestVariable("71c793c8-c07c-4f05-9733-50440b17cbb4")]
        public string ChromeProcessName
        {
            get { return _ChromeProcessName; }
            set { _ChromeProcessName = value; }
        }

        string _ExcelProcessName;

        /// <summary>
        /// Gets or sets the value of variable ExcelProcessName.
        /// </summary>
        [TestVariable("b6989404-023e-4060-855c-2fa167291930")]
        public string ExcelProcessName
        {
            get { return _ExcelProcessName; }
            set { _ExcelProcessName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.KillProcess(ChromeProcessName);
            Delay.Milliseconds(0);
            
            Ranorex.AutomationHelpers.UserCodeCollections.SystemLibrary.KillProcess(ExcelProcessName);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
